### ISSUE TITLE
Small improvement - add an icon to agent_icons folder?

### ISSUE THREAD

**Issue by ulricvbs** [MythicAgents/service_wrapper#2]
I generated an SVG for a "wrapper".
![service_wrapper](https://user-images.githubusercontent.com/54366361/173693196-44fe29ec-b460-4419-befe-9036d1063ded.svg)

Doesn't look too bad, but what do you think @its-a-feature?
![image](https://user-images.githubusercontent.com/54366361/173693502-82ff88f0-131a-48ae-a157-e3b4bfaf1ac5.png)

**Comment by its-a-feature** [comment]
Oh that's cool! How did you generate the SVG?

**Comment by ulricvbs** [comment]
I utilized Inkscape to manipulate images to create vectors.

**Comment by its-a-feature** [comment]
Nice! Did the original image come from somewhere? So that we can properly track attribution of the original creator. Once we have that, I'd be happy to add this :)

**Comment by ulricvbs** [comment]
Yes, I pulled a PNG from flaticon.com and converted it to SVG.

https://www.flaticon.com/free-icon/sweet_3050124

`<a href="https://www.flaticon.com/free-icons/sugar" title="sugar icons">Sugar icons created by Freepik - Flaticon</a>`

**Comment by its-a-feature** [comment]
Added!
